server:
  port: 8081
keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: SpringBootKeycloak
  resource: login-app
  public-client: true
  principal-attribute: preferred_username
  security-constraints[0]:
    authRoles[0]: user
    securityCollections[0]:
      patterns[0]: /customers/*